# Publish the joint states to joint_states.
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# old settigs(tested)

#front_left_steering_controller:
#  joint: rbsherpa_hl_front_left_wheel_steer_joint
#  type: effort_controllers/JointPositionController
#  pid: {p: 100.0, i: 0.1, d: 5.0}
#front_right_steering_controller:
#  joint: rbsherpa_hl_front_right_wheel_steer_joint
#  type: effort_controllers/JointPositionController
#  pid: {p: 100.0, i: 0.1, d: 5.0}
#back_left_steering_controller:
#  joint: rbsherpa_hl_back_left_wheel_steer_joint
#  type: effort_controllers/JointPositionController
#  pid: {p: 100.0, i: 0.1, d: 5.0}
#back_right_steering_controller:
#  joint: rbsherpa_hl_back_right_wheel_steer_joint
#  type: effort_controllers/JointPositionController
#  pid: {p: 100.0, i: 0.1, d: 5.0}
   
#left_front_controller:
#  joint: rbsherpa_hl_front_left_wheel_traction_joint
#  type: effort_controllers/JointVelocityController
#  pid: {p: 1.5, i: 10.0, d: 0.0}
#right_front_controller:
#  joint: rbsherpa_hl_front_right_wheel_traction_joint
#  type: effort_controllers/JointVelocityController
#  pid: {p: 1.5, i: 10.0, d: 0.0}
#left_rear_controller:
#  joint: rbsherpa_hl_back_left_wheel_traction_joint
#  type: effort_controllers/JointVelocityController
#  pid: {p: 1.5, i: 10.0, d: 0.0}
#right_rear_controller:
#  joint: rbsherpa_hl_back_right_wheel_traction_joint
#  type: effort_controllers/JointVelocityController
#  pid: {p: 1.5, i: 10.0, d: 0.0}

# New setting for wheels (it requires a test on the robot)

front_left_wheel_traction_joint_controller:
  type: effort_controllers/JointVelocityController
  joint: rbsherpa_hl_front_left_wheel_traction_joint
  pid: {p: 1.5, i: 10.0, d: 0.0}

front_left_wheel_steer_joint_controller:
  type: effort_controllers/JointPositionController
  joint: rbsherpa_hl_front_left_wheel_steer_joint
  pid: {p: 100.0, i: 0.1, d: 5.0}

front_right_wheel_traction_joint_controller:
  type: effort_controllers/JointVelocityController
  joint: rbsherpa_hl_front_right_wheel_traction_joint
  pid: {p: 1.5, i: 10.0, d: 0.0}

front_right_wheel_steer_joint_controller:
  type: effort_controllers/JointPositionController
  joint: rbsherpa_hl_front_right_wheel_steer_joint
  pid: {p: 100.0, i: 0.1, d: 5.0}

back_left_wheel_traction_joint_controller:
  type: effort_controllers/JointVelocityController
  joint: rbsherpa_hl_back_left_wheel_traction_joint
  pid: {p: 1.5, i: 10.0, d: 0.0}

back_left_wheel_steer_joint_controller:
  type: effort_controllers/JointPositionController
  joint: rbsherpa_hl_back_left_wheel_steer_joint
  pid: {p: 100.0, i: 0.1, d: 5.0}

back_right_wheel_traction_joint_controller:
  type: effort_controllers/JointVelocityController
  joint: rbsherpa_hl_back_right_wheel_traction_joint
  pid: {p: 1.5, i: 10.0, d: 0.0}

back_right_wheel_steer_joint_controller:
  type: effort_controllers/JointPositionController
  joint: rbsherpa_hl_back_right_wheel_steer_joint
  pid: {p: 100.0, i: 0.1, d: 5.0}







# Arm controllers

pan_controller:
  joint: rbsherpa_hl_torso_pantilt_pan_joint
  type: effort_controllers/JointPositionController
#  pid: {p: 10.0, i: 0.01, d: 40.0}
  pid: {p: 100.0, i: 0.01, d: 30.0}
lift_controller:
  joint: rbsherpa_hl_torso_elevator_joint
  type: effort_controllers/JointPositionController
  pid: {p: 10.0, i: 0.01, d: 50.0}

# Gimbal controllers

yaw_controller:
  joint: rbsherpa_hl_gimbal_yaw_joint
  type: effort_controllers/JointPositionController
  pid: {p: 50.0, i: 0.1, d: 5.0}
  
roll_controller:
  joint: rbsherpa_hl_gimbal_roll_joint
  type: effort_controllers/JointPositionController
  pid: {p: 50.0, i: 0.1, d: 5.0}
  
pitch_controller:
  joint: rbsherpa_hl_gimbal_pitch_joint
  type: effort_controllers/JointPositionController
  pid: {p: 50.0, i: 0.1, d: 5.0}  



