<?xml version="1.0"?>

<!-- Sherpa -->

<robot name ="sherpa" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!--from sherpa_ex-->

    <!-- Box Inertia -->
    <xacro:macro name="box_inertia" params="m h w d">
        <inertia 	ixx="${m*(w*w+d*d)/12}" ixy = "0.0" ixz = "0.0" 
        iyy="${m*(d*d+h*h)/12}" iyz = "0.0" 
        izz="${m*(w*w+h*h)/12}"/>
    </xacro:macro>

    <!-- Cylinder Inertia USELESS-->
    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertia  	ixx="${m*(3*r*r+h*h)/12}" ixy = "0.0" ixz = "0.0" 
        iyy="${m*r*r/2}" iyz = "0.0" 
        izz="${m*(3*r*r+h*h)/12}"/>
    </xacro:macro> <!--modified 10/05/2019 (swapped y and z inertia) -->


    <xacro:macro name="default_inertial_wheel" params="mass">
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="${mass}"/>
          <inertia
	      ixx="0.1" ixy="0.0" ixz="0.0"
	      iyy="0.1" iyz="0.0"
	      izz="0.1"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="default_inertial" params="mass">
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="${mass}"/>
          <inertia
	      ixx="0.1" ixy="0.0" ixz="0.0"
	      iyy="0.1" iyz="0.0"
	      izz="0.1"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="fake_inertial">
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="1e-5"/>
          <inertia
	      ixx="1e-6" ixy="0.0" ixz="0.0"
	      iyy="1e-6" iyz="0.0"
	      izz="1e-6"/>
        </inertial>
    </xacro:macro>


    <!-- Parameters -->
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="offset" value="0.0010"/>

    <!-- Chassis Property -->
    <xacro:property name="chassis_x" value="1.64340"/>
    <xacro:property name="chassis_y" value="1.0040"/>
    <xacro:property name="chassis_z" value="0.39440"/>
    <xacro:property name="chassis_field_height" value="0.46990"/>
    <!--tested-->
    <!--    <xacro:property name="mass" value="450.0"/>-->
    <!--new-->
    <xacro:property name="mass" value="5.0"/>

    <!--added offset of wheels from robotnik model  -->
    <xacro:property name="wheel_steer_offset_x" value="0.622" />
    <xacro:property name="wheel_steer_offset_y" value="0.367" />
    <xacro:property name="wheel_steer_offset_z" value="0.285" />
    <xacro:property name="wheel_traction_offset_x" value="0.0" />
    <xacro:property name="wheel_traction_offset_y" value="0.03" />
    <xacro:property name="wheel_traction_offset_z" value="-0.285" />

    <xacro:property name="track_width" value="0.755620"/>
    <xacro:property name="wheelbase" value="1.24570"/>

    <!-- Cable Box Property -->
    <xacro:property name="cb_x" value="0.060"/>
    <xacro:property name="cb_y" value="0.1750"/>
    <xacro:property name="cb_z" value="0.550"/>
    <xacro:property name="cb_origin_x" value="-0.5675"/> <!-- Origin wrt to chassis' frame -->
    <xacro:property name="cb_origin_y" value="0"/>
    <xacro:property name="cb_origin_z" value="0.833"/> <!-- Height of the top of the chassis wrt ground -->

    <!-- Wheel Parameters -->

    <xacro:property name="steer_z" value="0.060"/>
    <xacro:property name="steer_radius" value="0.11530"/>
    <xacro:property name="suspension_x" value="0.080"/>
    <xacro:property name="suspension_y" value="0.080"/>
    <xacro:property name="suspension_z" value="0.22560"/>
    <xacro:property name="wheel_radius" value="0.17430"/>
    <xacro:property name="wheel_width" value="0.11420"/>
    <!--tested-->
    <!--    <xacro:property name="wheel_mass" value="10.0"/>-->
    <!--new-->
    <xacro:property name="wheel_mass" value="1.0"/>

    <!-- Sensors -->

    <xacro:property name="sick_front_x" value="1.64340"/>
    <xacro:property name="sick_front_y" value="1.0040"/>
    <xacro:property name="sick_front_z" value="0.2548"/>

    <xacro:property name="sick_rear_x" value="1.64340"/>
    <xacro:property name="sick_rear_y" value="1.0040"/>
    <xacro:property name="sick_rear_z" value="0.2402"/>

    <!-- Arm Parameters -->

    <!-- lift_gun properties --> <!-- represents the total block lift -->
    <xacro:property name="lg_x" value="0.168109"/>
    <xacro:property name="lg_y" value="0.13725"/>
    <xacro:property name="lg_z" value="0.9420"/>
    <xacro:property name="lg_origin_x" value="${cb_origin_x+cb_x/2+lg_x/2}"/> <!-- Origin wrt chassis' frame -->
    <!--<xacro:property name="lg_origin_y" value="0.0"/>-->
    <!--<xacro:property name="lg_origin_z" value="${cb_origin_z}"/> <!- - Height of the top of the chassis wrt ground - ->-->


    <!-- lift_second_part properties -->
    <xacro:property name="lsp_x" value="0.04507"/>
    <xacro:property name="lsp_y" value="0.13725"/>


    <!-- pan properties -->
    <xacro:property name="pan_x" value="0.980915"/>
    <xacro:property name="pan_y" value="0.07"/>
    <xacro:property name="pan_z" value="0.04291"/>


    <xacro:property name="mu_1" value="9999999999999999999999999999999" />

</robot>
